data_dir = os.path.join('phys', 'groups', 'tev', 'scratch3', 'users', 'schuya', 'ColorTagging') 
octet_text = os.path.join(data_dir, 'Octet_Rotated_withDR.txt')
singlet_text = os.path.join(data_dir, 'Singlet_Rotated_withDR.txt')
octet_npy = os.path.join(data_dir, 'Octet_Rotated_withDR.npy')
singlet_npy = os.path.join(data_dir, 'Singlet_Rotated_withDR.npy')
